# Using Web Services
# https://www.py4e.com/lessons/servces
import xml.etree.ElementTree as ET

input = '''<stuff>
<comments>
<comment>
<name>Macauley</name>
<count>99</count>
</comment>
<comment>
<name>Barkley</name>
<count>98</count>
</comment>
<comment>
<name>Geordie</name>
<count>97</count>
</comment>
<comment>
<name>Yago</name>
<count>95</count>
</comment>
<comment>
<name>Lilliana</name>
<count>95</count>
</comment>
<comment>
<name>Salsabeel</name>
<count>94</count>
</comment>
<comment>
<name>Zeeshan</name>
<count>94</count>
</comment>
<comment>
<name>Erdehan</name>
<count>92</count>
</comment>
<comment>
<name>Shaarvin</name>
<count>85</count>
</comment>
<comment>
<name>Yasemin</name>
<count>84</count>
</comment>
<comment>
<name>Inga</name>
<count>84</count>
</comment>
<comment>
<name>Rai</name>
<count>82</count>
</comment>
<comment>
<name>Kalen</name>
<count>80</count>
</comment>
<comment>
<name>Misba</name>
<count>76</count>
</comment>
<comment>
<name>Aiman</name>
<count>74</count>
</comment>
<comment>
<name>Amolpreet</name>
<count>74</count>
</comment>
<comment>
<name>Evelina</name>
<count>72</count>
</comment>
<comment>
<name>Mustapha</name>
<count>70</count>
</comment>
<comment>
<name>Seonaidh</name>
<count>70</count>
</comment>
<comment>
<name>Keilee</name>
<count>68</count>
</comment>
<comment>
<name>Ryo</name>
<count>66</count>
</comment>
<comment>
<name>Mati</name>
<count>66</count>
</comment>
<comment>
<name>Aimie</name>
<count>65</count>
</comment>
<comment>
<name>Leyna</name>
<count>64</count>
</comment>
<comment>
<name>Divine</name>
<count>63</count>
</comment>
<comment>
<name>Abdulkhader</name>
<count>62</count>
</comment>
<comment>
<name>Devan</name>
<count>61</count>
</comment>
<comment>
<name>Marcquis</name>
<count>61</count>
</comment>
<comment>
<name>Jadyn</name>
<count>55</count>
</comment>
<comment>
<name>Cathleen</name>
<count>54</count>
</comment>
<comment>
<name>Karmyn</name>
<count>50</count>
</comment>
<comment>
<name>Shalamar</name>
<count>49</count>
</comment>
<comment>
<name>Darryn</name>
<count>49</count>
</comment>
<comment>
<name>Wezi</name>
<count>48</count>
</comment>
<comment>
<name>Norman</name>
<count>35</count>
</comment>
<comment>
<name>Inara</name>
<count>34</count>
</comment>
<comment>
<name>Tamarah</name>
<count>32</count>
</comment>
<comment>
<name>Dimitri</name>
<count>32</count>
</comment>
<comment>
<name>Marcella</name>
<count>28</count>
</comment>
<comment>
<name>Frankie</name>
<count>28</count>
</comment>
<comment>
<name>Connel</name>
<count>25</count>
</comment>
<comment>
<name>Enya</name>
<count>24</count>
</comment>
<comment>
<name>Sharoz</name>
<count>23</count>
</comment>
<comment>
<name>Aarifah</name>
<count>22</count>
</comment>
<comment>
<name>Tyane</name>
<count>17</count>
</comment>
<comment>
<name>Ruairidh</name>
<count>10</count>
</comment>
<comment>
<name>Leyton</name>
<count>7</count>
</comment>
<comment>
<name>Salma</name>
<count>7</count>
</comment>
<comment>
<name>Lucy</name>
<count>4</count>
</comment>
<comment>
<name>Leilani</name>
<count>1</count>
</comment>
</comments>
</commentinfo>
</stuff>'''
stuff = ET.fromstring("/usr/lib/python3.8/xml/etree/ElementTree.py")
x = stuff.findall('comments/comment')
print('user count: ', len(x))